### ISSUE TITLE
tracking issue: 改进 JSON 数据格式输出（或者改进 CLI 与 WebUI 交互）

### ISSUE THREAD

**Issue by zjp-CN** [os-checker/os-checker#14]
对于以下 `repos.yaml` 和网页部署结果，有许多需要改进的地方（图片标注了顺序）

```yaml
os-checker/os-checker-test-suite:
  all: true

arceos-org/arceos:
  all: true

# 以下库是随便选的
kern-crates/CSpace: 
  all: true

elliott10/e1000-driver:
  all: true

kern-crates/ByteOS:
  all: true

shilei-massclouds/axdtb:
  all: true
```

![](https://github.com/user-attachments/assets/19b3f550-209c-4e85-ab80-65ddbba139af)

### 属于 UI 和 CLI 交互的问题

- [ ] 1. 没有合并相同 user 的仓库：比如 kern-crates 只应该存在一个 Tree，但目前根据 user/repo 来构建 Tree。这是一个交互问题：我认为通过 user 和 user/repo 作为展开的根节点都有意义。鉴于这个改进需要考虑更多设计，暂时搁置。（因为我想要支持 user 视图、 repo 视图之类的详情页面）
- [ ] 2. 目前 Tree 对 monorepo （一个仓库存放多个项目/库）是友好的，但对 multi-repo （一个仓库只放一个项目/库）不友好。对于 multi-repo，减少重复的 children，让单仓库单项目只有一层会更精简。我们可以不改变现有的 JSON 的结果，在 WebUI 代码库完成这个。
- [ ] 3. 列筛选不应应用到数值列：对计数列筛选数值是没意义的（因为后面会支持对列排序）；这是一个纯 WebUI 的问题 。
- [ ] 4. totoal count 的统计逻辑问题：目前对 `Unformatted(File|Line)` 纳入总计数，有些不正确，因为它们是对同一个不良检查结果的不同角度进行统计的 —— 相对的， `Clippy(Error|Warn)` 纳入总计数是正确的，因为它们对不同的不良检查结果统计；不过将 Clippy 和 Unformatted 进行统计，也不太正确。总计数的逻辑似乎也是一个交互问题，把它变成动态计算会更人性化一些：目前已经支持指定显示哪些列，那么只对指定计数列做总计数，更直观，也把统计逻辑上的问题抛给了使用者。

关于最后一点”总统计“，我们还没有把基于文件的统计结果放到 WebUI，我认为它们更适合放到 repo 详情视图。（虽然可以在总视图显示不良文件总计数？？？这个文件总计数的逻辑比把 Unformatted + Clippy 计算到一起会更通顺。
